name: 'Update Postmant Environments'
description: 'Merges the values from a public and a private environment in order to .'

inputs:
  public_environment:
    description: 'The name of the variable to update.'
    required: true
  secret_environment:
    description: 'The value to set for the variable.'
    required: true
  target_environment:
    description: ''
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        POSTMAN_ENV_PUBLIC: ${{ inputs.public_environment }}
        POSTMAN_ENV_SECRET: ${{ inputs.secret_environment }}
        POSTMAN_ENV_TARGET: ${{ inputs.target_environment }}
      run: |
        echo "Running Postman environment update script..."
        python ./src/action.py 