name: 'Update Postmant Environments'
description: 'Merges the values from a public and a private environment in order to .'

inputs:
  public_environment:
    description: 'The id of the Public environment to get the public variables from.'
    required: true
  secret_environment:
    description: 'The id of the Secret environment to update, containing the secrets to be injected on the dest env.'
    required: true
  target_environment:
    description: 'The id of the Target environment to update.'
runs:
  using: "composite"
  steps:      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
      shell: bash

    
    - name: Check out to repo
      uses: actions/checkout@v4

    - name: Run script
      uses: ./
      env:
        POSTMAN_API_KEY: ${{ inputs.POSTMAN_API_KEY }}
        POSTMAN_ENV_PUBLIC: ${{ inputs.public_environment }}
        POSTMAN_ENV_SECRET: ${{ inputs.secret_environment }}
        POSTMAN_ENV_TARGET: ${{ inputs.target_environment }}
      run: |
        echo "Running Postman environment update script..."
        python src/action.py 
      shell: bash